### ISSUE TITLE
Should use the new build_log endpoint

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_error_page#1]
I've created a richer endpoint for this page that exposes more metadata and compiler output for debugging purposes.

    https://api.qmk.fm/v1/keyboards/build_log

Each entry is a dictionary with two keys:

* `works` - Boolean indicating whether or not the keyboard builds in configurator
* `message` - Compiler output for that keyboard

**Comment by yanfali** [comment]
Fix with e8db91c5cc893cc1a7ef37f2cb6e5b6dad751948
